### PR TITLE
feat: allow empty username/password; fix text

### PR DESCRIPTION
**Pull request by Shadow53**
I believe the added quotation marks are necessary to allow an empty password with Gemfury. I also fixed the description text for the username/password inputs, which were copied from the URL input.

### CODE REVIEW

**Comment by dbanty** [comment]
Will the default of NOT_SPECIFIED actually omit the password field altogether? I thought it was just a string, so omitting the password would do `poetry config http-basic.private "my_username" "NOT_SPECIFIED"`.

I think we need an if to check it or change the default to empty string if possible.

**Comment by Shadow53** [comment]
I essentially added both. Defaulting to an empty string makes more sense IMO, and I modified the check for URL and added a check for username to match.

For reference, `[ ]` uses the POSIX `test` command while `[[ ]]` is a bash-specific builtin, and `-n` is true on non-empty strings, which `-z` is true for empty strings.

**Comment by dbanty** [comment]
@Shadow53 have you / can you test from a separate project pointing at this branch to verify it all works correctly?

**Comment by Shadow53** [comment]
AFAICT this should exercise the changes and passes without issue: https://github.com/triaxtec/cat/runs/2392027899

**Pull request merged**
